/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:b5ddf56c-176f-4542-94e0-cf555f454ac7",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_jmbiayOb4",
  aws_user_pools_web_client_id: "7gvpd3iutdat7ua6d2hjvoi4ov",
  oauth: {
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://flamboyant-golick-e73a92.netlify.app/",
    redirectSignOut: "https://flamboyant-golick-e73a92.netlify.app/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
};

export default awsmobile;
