/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:8a8f5935-3e40-4942-91ba-a410eebcf51f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_1jGn5Ls3c",
    "aws_user_pools_web_client_id": "3urn2p882eh2k0c55v7q31r380",
    "oauth": {
        "domain": "workoutmanager-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
